
<?php

/**
 * @var \Visma\ProductLabel\Block\Label $myBlock
 */
$myBlock = \Magento\Framework\App\ObjectManager::getInstance()->get('Visma\ProductLabel\Block\Label');

echo $this->getLayout()
    ->createBlock('Visma\ProductLabel\Block\Label')
    ->setTemplate("Vimsa_ProductLabel::getlabel.phtml")
    ->toHtml();


$currentProduct = $myBlock->getCurrentProduct();

if ($currentProduct->getSpecialPrice() !== null ): ?>

<h1 class="label" style="background-color:<?php echo $myBlock->getColour();  ?>">! <?php echo $myBlock->getLabelText();  ?></h1>

<?php endif; ?>